name: Run removerML Script Manually

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: 'Input file to process (relative to repo root)'
        required: true
        default: 'removerML/input.jpg'
      output_file:
        description: 'Output file to save (relative to repo root)'
        required: true
        default: 'removerML/output.png'

jobs:
  run-removerml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run removerML script
      run: |
        python removerML/your_script.py --input ${{ github.event.inputs.input_file }} --output ${{ github.event.inputs.output_file }}

    - name: Upload output artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-file
        path: ${{ github.event.inputs.output_file }}
